  #################################################################
 ##   Manhunt - Dream and GeorgeNotFound's replica of manhunt!  ##
#################################################################

# Permission nodes:
# manhunt.hunter.add - Gives player permission to add players to the hunter list. (/manhunt hunter add [PLAYER])
# manhunt.hunter.remove - Gives player permission to remove players from the hunter list. (/manhunt hunter remove [PLAYER])
# manhunt.speedrunner.add - Gives player permission to make a player a speedrunner. (/manhunt speedrunner add [PLAYER])
# manhunt.speedrunner.remove - Gives player permission to remove a player from being the speedrunner. (/manhunt speedrunner remove [PLAYER])
# manhunt.reload - Gives player permission to reload the plugin config.
# manhunt.start - Gives player permission to start the game.

Command:
  Sender:
