suffix:
  character-max: 10
  character-min: 3
  banned-characters: # WARNING: Racial slurs at the bottom, already completed.
    - "!"            # WARNING: Racial slurs at the bottom, already completed.
    - "@"            # WARNING: Racial slurs at the bottom, already completed.
    - "#"            # WARNING: Racial slurs at the bottom, already completed.
    - "%"
    - "_"
    - "{"
    - "}"
    - "["
    - "]"
    - "\\"
    - "|"
    - ":"
    - "'"
    - '"'
    - "/"
    - "nigga"
    - "n1gga"
    - "n1ga"
    - "niga"
    - "nigg4"
    - "n1gg4"
    - "nig4"
    - "aggin"
    - "n1g4"
    - "migga"
    - "miga"
    - "m1ga"
    - "m1g4"
    - "nigger"
    - "n1gg3r"
    - "n1g3r"
    - "n1ger"
    - "niger"
    - "migger"
    - "m1gg3r"
    - "m1g3r"
    - "mig3r"
    - "niiga"
    - "niiggaa"
    - "nniiggaa"
    - "nn11gg44"
    - "n11ggaa"
    - "n11ga"
    - "n11gga"
    - "n11gaa"
    - "n1gaa"